# Generated by Django 5.2.1 on 2025-05-27 05:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=64)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=False)),
            ],
        ),
    ]
